# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      sudo npm install -g snyk

      # create variable in Pipelines called 'SNYK_TOKEN' and securely save your Snyk token value
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables

      sudo snyk auth $(SNYK_TOKEN)
    displayName: 'install snyk'

  - script: |
      sudo snyk test
    displayName: 'sudo snyk test'